["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
ERC721_original = [
    "lib/cairo_contracts/src/openzeppelin/token/erc721/presets/ERC721MintableBurnable.cairo",
]
ERC721_custom = [
    "src/contracts/ERC721Custom.cairo",
]

["protostar.shared_command_configs"]
cairo-path = ["lib/cairo_contracts/src"]